server:
  port: 9000

spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignoredPatterns: /*-server/**
  routes:
    order-server-route:
      path: /order/**
      serviceId: ORDER-SERVER
  host:
    socket-timeout-millis: 6000  #默认1000
    connect-timeout-millis: 6000  #默认2000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000